# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59478e1126223bbb11bfeeeb81678231e29e4c18edd32a315d6ecd60fe7268602f4efb6e2146b39ca94cb192d2c3781ca6c1e39e94f4a4d9a2762f48a7582cc5

test:
  secret_key_base: 3c171728ccb80dbd6fc003852623fcf6bf55813b8dbc521978d905406590b2ea4a2dd535721eeac050e06c7446228d71caf39da8591046137acde883bcb74691

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
